parameters:
#    backcon_parametres_general.example.class: Backcon\Parametres\GeneralBundle\Example

services:
#    backcon_parametres_general.example:
#        class: %backcon_parametres_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
