parameters:
#    backcon_parametres_congres.example.class: Backcon\Parametres\CongresBundle\Example

services:
#    backcon_parametres_congres.example:
#        class: %backcon_parametres_congres.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
