parameters:
#    backcon_parametres_reservation.example.class: Backcon\Parametres\ReservationBundle\Example

services:
#    backcon_parametres_reservation.example:
#        class: %backcon_parametres_reservation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
